# Generated by Django 5.1.6 on 2025-02-26 17:44

import users.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_user_last_updated_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, storage=users.storage.AvatarStorage(), upload_to='avatars/'),
        ),
    ]
