# Use Node.js base image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package files
COPY frontend/package.json frontend/package-lock.json ./

# Install dependencies
RUN npm install

# Copy app source
COPY frontend ./

# Build frontend
RUN npm run build

# Expose port
EXPOSE 5173

# Start server
CMD ["npm", "run", "preview"]