
FROM node:22 AS builder

WORKDIR /app/frontend


COPY frontend/package.json frontend/package-lock.json ./
RUN npm install --frozen-lockfile


COPY frontend ./

RUN chmod -R 777 /app/frontend

RUN npm run build

FROM nginx:latest AS production

WORKDIR /app

RUN rm -rf /usr/share/nginx/html/*
RUN rm -rf /app/frontend/*

COPY --from=builder /app/frontend/dist /app/frontend

COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]