# Generated by Django 5.1.6 on 2025-02-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_remove_order_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('shipped', 'Shipped'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
