# Generated by Django 5.1.6 on 2025-02-27 05:38

import django.db.models.deletion
import sales.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_invoice_due_date_salesorder_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=sales.storage.InvoiceStorage(), upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sales_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sales.salesorder'),
        ),
    ]
