# Generated by Django 5.1.6 on 2025-02-27 08:24

import sales.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_invoice_pdf_file_alter_invoice_sales_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=sales.storage.InvoiceStorage(), upload_to='pdf/'),
        ),
    ]
