# Generated by Django 5.1.6 on 2025-02-24 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='user',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the product.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the product.', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product in KZT.', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available stock quantity.')),
                ('image', models.ImageField(blank=True, help_text='Product image.', null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the product was added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp.')),
                ('category', models.ForeignKey(blank=True, help_text='Category of the product.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('user', models.ForeignKey(help_text='Owner of the product listing.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
