# Generated by Django 5.1.6 on 2025-02-26 20:16

import django.db.models.deletion
import products.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_productlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image.', null=True, storage=products.storage.ProductStorage(), upload_to='products/'),
        ),
    ]
